import React from 'react';
import { Sparkles, ClipboardPaste, PenLine } from 'lucide-react';

const METHODS = [
  {
    id: 'generate',
    title: 'Generate with Gemini AI',
    description: 'Generate quiz questions automatically from a topic.',
    icon: Sparkles,
    accent: 'from-indigo-600/30 to-purple-600/20 border-indigo-500/50 hover:border-indigo-400',
    iconColor: 'text-indigo-400',
  },
  {
    id: 'paste',
    title: 'Paste & Analyze Questions',
    description: 'Import questions generated by ChatGPT, Claude, Gemini, or any AI.',
    icon: ClipboardPaste,
    accent: 'from-emerald-600/20 to-teal-600/10 border-emerald-500/40 hover:border-emerald-400',
    iconColor: 'text-emerald-400',
  },
  {
    id: 'manual',
    title: 'Create Manually',
    description: 'Build questions yourself with the classic question editor.',
    icon: PenLine,
    accent: 'from-slate-700/30 to-slate-800/20 border-slate-600/50 hover:border-slate-400',
    iconColor: 'text-slate-300',
  },
];

export const CreateMethodSelector = ({ selected, onSelect }) => {
  return (
    <div className="space-y-4">
      <h2 className="text-2xl font-extrabold text-white font-outfit">Create Questions</h2>
      <p className="text-sm text-slate-400">Choose how you want to add questions to your quiz.</p>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {METHODS.map((method) => {
          const Icon = method.icon;
          const isSelected = selected === method.id;

          return (
            <button
              key={method.id}
              type="button"
              onClick={() => onSelect(method.id)}
              className={`text-left p-6 rounded-2xl border bg-gradient-to-br transition-all duration-300 ${
                method.accent
              } ${isSelected ? 'ring-2 ring-indigo-500 scale-[1.02] shadow-lg shadow-indigo-500/20' : 'opacity-90 hover:opacity-100'}`}
            >
              <div className={`w-10 h-10 rounded-xl bg-black/30 flex items-center justify-center mb-4 ${method.iconColor}`}>
                <Icon className="w-5 h-5" />
              </div>
              <h3 className="font-bold text-white text-base mb-2">{method.title}</h3>
              <p className="text-xs text-slate-400 leading-relaxed">{method.description}</p>
            </button>
          );
        })}
      </div>
    </div>
  );
};
